Pearson correlation coefficient is a measure of the linear relationship between two variables. Suppose
you have collected data on the amount of time students spend studying for an exam and their final exam
scores. Calculate the Pearson correlation coefficient between these two variables and interpret the result.

In [ ]:
import pandas as pd


# Sample dataset
df = pd.DataFrame({
    'Time': [5, 6, 7, 8, 9, 10, 2, 2, 4],
    'Score': [50, 55, 60, 65, 70, 75, 30, 35, 40]  # Example exam scores
})

df.corr()
#This data shows that student who students for more time have more score.So time and score are directly realted to eachother.

           Time     Score
Time   1.000000  0.993375
Score  0.993375  1.000000


Q2. Spearman's rank correlation is a measure of the monotonic relationship between two variables.
Suppose you have collected data on the amount of sleep individuals get each night and their overall job
satisfaction level on a scale of 1 to 10. Calculate the Spearman's rank correlation between these two
variables and interpret the result.

In [ ]:
import pandas as pd

# Example dataset: Sleep hours vs Job satisfaction
data = {
    'Sleep_Hours': [4, 5, 6, 5, 7, 6, 8, 7, 9, 6, 5, 7, 8, 4, 6],
    'Job_Satisfaction': [3, 4, 5, 4, 6, 5, 8, 7, 9, 6, 4, 7, 8, 3, 5]  # scale 1-10
}

df = pd.DataFrame(data)
df.corr(method='spearman')
# If sleep hour is more than job satisfaction is more

                  Sleep_Hours  Job_Satisfaction
Sleep_Hours           1.00000           0.98624
Job_Satisfaction      0.98624           1.00000

3. Suppose you are conducting a study to examine the relationship between the number of hours of
exercise per week and body mass index (BMI) in a sample of adults. You collected data on both variables
for 50 participants. Calculate the Pearson correlation coefficient and the Spearman's rank correlation
between these two variables and compare the results.

In [ ]:
import pandas as pd
import numpy as np

# Sample data
np.random.seed(42)
exercise_hours = np.random.randint(0, 10, 50)
bmi = 30 - (exercise_hours * np.random.uniform(0.5, 1.0, 50)) + np.random.normal(0, 1, 50)

df = pd.DataFrame({
    'Exercise_Hours': exercise_hours,
    'BMI': bmi
})

df.head()

In [5]:
df.corr()

                  Sleep_Hours  Job_Satisfaction
Sleep_Hours          1.000000          0.983752
Job_Satisfaction     0.983752          1.000000

In [6]:
df.corr(method='spearman')

                  Sleep_Hours  Job_Satisfaction
Sleep_Hours           1.00000           0.98624
Job_Satisfaction      0.98624           1.00000

Q4. A researcher is interested in examining the relationship between the number of hours individuals
spend watching television per day and their level of physical activity. The researcher collected data on
both variables from a sample of 50 participants. Calculate the Pearson correlation coefficient between
these two variables.

In [7]:
import pandas as pd
import numpy as np

# For reproducibility
np.random.seed(42)

# Simulate data for 50 participants
tv_hours = np.random.randint(0, 6, 50)  # TV hours per day (0–5)
physical_activity = 10 - tv_hours + np.random.normal(0, 1, 50)  # More TV → less activity

# Create DataFrame
df = pd.DataFrame({
    'TV_Hours': tv_hours,
    'Physical_Activity': physical_activity
})

df.corr()

                   TV_Hours  Physical_Activity
TV_Hours           1.000000          -0.824417
Physical_Activity -0.824417           1.000000

In [11]:
import pandas as pd

# Dataset from survey
d = {
    'Age': [25, 42, 37, 19, 31, 28],
    'Preferred_Brand': ['Coke', 'Pepsi', 'Mountain Dew', 'Coke', 'Pepsi', 'Coke']
}
df=pd.DataFrame(d)
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['new_p']=le.fit_transform(df[['Preferred_Brand']])
df[['Age','new_p']].corr()

c:\Users\91897\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

            Age     new_p
Age    1.000000  0.769175
new_p  0.769175  1.000000

Q6. A company is interested in examining the relationship between the number of sales calls made per day
and the number of sales made per week. The company collected data on both variables from a sample of
30 sales representatives. Calculate the Pearson correlation coefficient between these two variables.

In [8]:
import pandas as pd
import numpy as np

# For reproducibility
np.random.seed(42)

# Simulate data for 30 sales reps
sales_calls_per_day = np.random.randint(5, 21, 30)  # 5–20 calls per day
weekly_sales = sales_calls_per_day * np.random.uniform(0.8, 1.2, 30)  # Sales roughly proportional to calls

# Create DataFrame
df = pd.DataFrame({
    'Sales_Calls_Per_Day': sales_calls_per_day,
    'Weekly_Sales': weekly_sales
})

df.corr(method='spearman')

                     Sales_Calls_Per_Day  Weekly_Sales
Sales_Calls_Per_Day             1.000000      0.950858
Weekly_Sales                    0.950858      1.000000